### PR TITLE
Requires at least gradle 4.10

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

readme incorrectly specified minimum gradle version.

## After this PR

Fxied

### CODE REVIEW

**Comment by ferozco** [comment]
How did we verify that it worked with 4.9?

**Comment by dansanduleac** [comment]
It was just a guess. It's actually 4.10 that it works with, tested locally on a project. In 4.9 it fails with:
```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.provider.ListProperty.addAll([Ljava/lang/Object;)V
        at com.palantir.gradle.dist.service.JavaServiceDistributionExtension.<init>(JavaServiceDistributionExtension.java:70)
```

**Comment by ferozco** [comment]
👍
