### PR TITLE
Support gradle 6.4

### PR DESCRIPTION
**Pull request by ferozco**
## Before this PR
`run` task would fail at configuration time with gradle >= 6.4 because of an implementation change in `JavaExec` which broke the way we lazily configured the main class. 

## After this PR
==COMMIT_MSG==
`run` works with gradle 6.4 and up
==COMMIT_MSG==

### CODE REVIEW

**Review by dansanduleac — APPROVED** [review]

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java [hunk 1]
```diff
@@ -217,12 +218,16 @@ public void apply(Project project) {
...
-            });
+            if (GradleVersion.current().compareTo(GradleVersion.version("6.4")) < 0) {
+                task.doFirst(new Action<Task>() {
+                    @Override
+                    public void execute(Task _task) {
+                        task.setMain(mainClassName.get());
+                    }
+                });
+            } else {
+                task.getMainClass().set(mainClassName);
```
Comment (iamdanfox) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java:229]: would this just throw a NoSuchMethodError if we ran it on gradle 6.3?

Comment (ferozco) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java:229]: yup

**Comment by iamdanfox** [comment]
Do we have any tests that run with various different `gradleVersion`s?
